commit

diff --git a/Jenkinsfile.nodejs b/Jenkinsfile.nodejs
--- a/Jenkinsfile.nodejs
+++ b/Jenkinsfile.nodejs
@@ -33,17 +33,16 @@ pipeline {
     stage('Install deps') {
       steps {
         script {
-          writeFile file: 'run_with_pipefail.sh', text: '''
-            #!/bin/bash
-            set -o pipefail
-            if [ -f package-lock.json ]; then
-              npm ci --prefer-offline --no-audit --progress=false
-            else
-              npm install --prefer-offline --no-audit --progress=false
-            fi
-          '''
-          sh 'chmod +x run_with_pipefail.sh'
-          sh 'bash ./run_with_pipefail.sh'
+          script {
+            writeFile file: 'run_with_pipefail.sh', text: '''
+              #!/usr/bin/bash
+              set -o pipefail
+              echo "This is running in bash"
+              ls not_a_real_file | grep something || echo "Pipefail triggered"
+            '''
+            sh 'chmod +x run_with_pipefail.sh'
+            sh 'bash ./run_with_pipefail.sh'
+          }
         }
       }
     }
